### ISSUE TITLE
401 Unauthorized - Ionic 2 Emulate iOS

### ISSUE THREAD

**Issue by dhndeveloper** [micky2be/superlogin-client#11]
Hello,

I got this working very well with Chrome. However, when I went to deploy it to my phone and emulator I'm getting a 401 error and "uncaught promise [object object]" when I'm trying to login. 

Could this have to do with the local storage settings? Ionic 2 uses its own LocalStorage. 

Thanks!

**Comment by micky2be** [comment]
I'm not familiar with Ionic. But we don clear the localStorage so you should be safe.

You might get an `"uncaught promise [object object]"` if there is no catch for a Promise that is been rejecting.
Can be on my end, I'll take a look, but it shouldn't affect the execution of your app.

If you could gimme some code and tell when it happens I would be easier for me to help you.

**Comment by dhndeveloper** [comment]
I figured it out. It was a mistake on my end. Thanks!
