### ISSUE TITLE
Request: VerifyPassword

### ISSUE THREAD

**Issue by dhndeveloper** [micky2be/superlogin-client#12]
Is it possible to implement verify password to this api? I'd like to do offline user authentication if possible.

**Comment by micky2be** [comment]
What do you mean exactly?

The current implementation of superlogin-client si to talk to superlogin.
Not sure you'll be able to do anything offline without the backend side.

**Comment by dhndeveloper** [comment]
Superlogin has superlogin.verifypassword(hashobj, password). Does that require backend to work? From what I could tell from the code, it didn't look like it but then again I'm not a pro.

I'm just wondering if there is a way to login a user offline if you save their user data that comes back when you log them in.

**Comment by micky2be** [comment]
Well you cannot use `superlogin` on the browser.
And `superlogin-client` is just an SDK, without the backend part it's useless.
So unless someone make a version for browser you won't be able to do it.
