### ISSUE TITLE
Refresh triggers refresh?

### ISSUE THREAD

**Issue by peteruithoven** [micky2be/superlogin-client#15]
It looks like calling `refresh()` is handled just like any other request which triggers checkRefresh which can trigger refresh again? 
`checkRefresh` contains a `_refreshInProgress` check, but this is only set to true from the checkRefresh method, which doesn't prevent a second `refresh()` call. Shouldn't `_refreshInProgress` be set from the `refresh` method?

**Comment by peteruithoven** [comment]
Ah I understand this isn't that simple because users can provide an alternative refresh method. (Something that isn't documented) 
Maybe we can create a refresh function that manages that `refreshInProgress` flag and calls the current refresh handler (which should probably always return a promise).

**Comment by micky2be** [comment]
The fact that it's possible for a user to set his own refresh method is pure legacy.
I will have no problem removing it. 

So fill free to update the refresh method with your proposal on a PR.

**Comment by peteruithoven** [comment]
Ah awesome, that makes things easier. I'll do a PR today.

**Comment by peteruithoven** [comment]
Did the pr: https://github.com/micky2be/superlogin-client/pull/19
