### ISSUE TITLE
Hot reloading issue

### ISSUE THREAD

**Issue by peteruithoven** [micky2be/superlogin-client#17]
With the hot reloading systems of [SystemJS](https://github.com/systemjs/systemjs) ([jspm](http://jspm.io/)); [systemjs-hot-reloader](https://github.com/capaj/systemjs-hot-reloader) superlogin-client's request interseptors are stacking up, per hot reload. This means the checkRefresh is called the amount of times a hot reload was performed. 

This is party caused by superlogin-client returning the instance instead of the class. Which means the instance isn't recreated when the package is re-imported. Then the user code will call the configure again which will add another request interseptor to check if the session needs to be refreshed. 

I'm looking into solutions that are hopefully not systemjs-hot-reloader specific or won't break in other module loading systems.

**Comment by micky2be** [comment]
Hmmm that would mean that the axios instance is still alive.
In the constructor of SuperloginClient we create a new instance of Axios (L31).
Try to move it to the configure method.

**Comment by peteruithoven** [comment]
Good point, that might also be easier and less specific to it's implementation than clearing it's handlers.

**Comment by peteruithoven** [comment]
I've updated my pull request: https://github.com/micky2be/superlogin-client/pull/18/commits/583b8dbd4d820a2fd6bfaad43b97a10f0ce2319a

One downside might be that people who used getHttp in between (super edge case) will be using an old , unused, instance.

**Comment by micky2be** [comment]
This is bad indeed and could create a memory leak.

**Comment by micky2be** [comment]
Included in v0.3.0
