### ISSUE TITLE
Adding a shared database

### ISSUE THREAD

**Issue by OnnoGabriel** [micky2be/superlogin-client#23]
Is there a function in superlogin-client similar to to the `addUserDB()` function in the original superlogin module? I need to add new CouchDB databases, which can be shared by multiple users.

**Comment by micky2be** [comment]
You should be able to find the URLs of your custom DB using #getDbUrl(<dbName>).
Basically all the database a user can access are visible under the property `userDBs` of the session.

**Comment by OnnoGabriel** [comment]
Yes, I know about `userDBs`. But is there a way to create a shared database on the CouchDB server from client site?

**Comment by micky2be** [comment]
No there is no api for it.
If your feel It's really necessary you should talk with @colinskow to add a route for it.
But from my perspective it goes beyond the current scope.
Such an api would mostly be needed for cms with admin permission.

**Comment by OnnoGabriel** [comment]
Ah, I misunderstood superlogin's `addUserDB()`. It is only adding existing databases to a user, but cannot create a new one. Thanks for your answers!
