### ISSUE TITLE
possible this bug?

### ISSUE THREAD

**Issue by staxmanade** [micky2be/superlogin-client#3]
Noticing that the `this` object [here](https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L472) is referencing the `window` object and not the expected instance of `Superlogin`.

Thinking it's because it may need [this line](https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L469) to change from this:

```
            const _oauthInterval = setInterval(function () {
```

to this

```
            const _oauthInterval = setInterval(() => {
```

Or [this line](https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L477) from this:

```
            }, 500);
```

to this

```
            }.bind(this), 500);
```

I noticed it when I click the "close" button on my oauth browser window.

Thoughts?

**Comment by micky2be** [comment]
Good catch.
Could you send a PR with your first proposal.

**Comment by staxmanade** [comment]
@micky2be will do. Before I do, can you tell me the purpose of `this.authComplete = true;` It only appears to be set once - but never used? Am I missing something?
