### ISSUE TITLE
Duplicate identifier 'Promise' @types

### ISSUE THREAD

**Issue by dhndeveloper** [micky2be/superlogin-client#31]
Hello,

I'm getting this error with the latest version of superlogin-client. The build works without errors with v0.2.3. 

I figured out this problem by starting the latest version of ionic where they brought back webpack. I added back in superlogin-client and then got these errors.

I'm good for now using 0.2.3. I think.

18:28:36]  typescript: node_modules/@types/es6-promise/index.d.ts, line: 11 
            Duplicate identifier 'Promise'. 

      L10:  * If you call reject your promise is rejected with the object passed to reject.
      L11:  * For consistency and debugging (eg stack traces), obj should be an instanceof Error.
      L12:  * Any errors thrown in the constructor callback will be implicitly passed to reject().

[18:28:36]  typescript: node_modules/@types/es6-promise/index.d.ts, line: 42 
            Duplicate identifier 'Promise'. 

      L42:  function resolve<T>(value?: T | Thenable<T>): Promise<T>;

[18:28:36]  typescript: node_modules/typescript/lib/lib.es2015.iterable.d.ts, line: 141 
            Duplicate identifier 'Promise'. 

     L140:      race<T>(values: Iterable<T | PromiseLike<T>>): Promise<T>;
       41:  }

[18:28:36]  typescript: node_modules/typescript/lib/lib.es2015.promise.d.ts, line: 20 
            Duplicate identifier 'Promise'. 

      L19:  * Attaches callbacks for the resolution and/or rejection of the Promise.
      L20:  * @param onfulfilled The callback to execute when the Promise is resolved.
      L21:  * @returns A Promise for the completion of which ever callback is executed.

[18:28:36]  typescript: node_modules/typescript/lib/lib.es2015.promise.d.ts, line: 187 
            Duplicate identifier 'Promise'.

**Comment by micky2be** [comment]
I just started to get the same problem on my project as well.
This is due to typings not handling duplicate dependencies ([See known issues](https://github.com/typings/typings/blob/master/docs/known-issues.md#global-dependencies))

Typescript definition has been added in v0.4.0, you should be safe to use v0.3.0.

**Comment by micky2be** [comment]
As a fix for superlogin-client what I can do for now is to remove the typescript definition.
I will leave the file in the repo as a sample that people like you could include in their project.
I'll put it back once typings fixed this issue.

How do you feal about that?

**Comment by dhndeveloper** [comment]
Oh I see. Yes, sounds good to me. Thanks!

**Comment by numerized** [comment]
Hi There, I've got the exact same problem.
As a temporary fix, I've renamed one of the two declaration of Promise.

**Comment by micky2be** [comment]
@numerized  Could you let me what you did.
Here I use es6-promise only for the the typescript definition

**Comment by Shocoben** [comment]
Hello, I have the same problem, as I stated here [on the ionic forum](https://forum.ionicframework.com/t/conflict-with-types-es6-promise-cause-crash-on-build/71267)

@micky2be What do you mean by "is to remove the typescript definition", are you talking about superlogin-client.d.ts ? 

Because for me the temporary solution was to `npm uninstall @types/es6-promise`

**Comment by numerized** [comment]
@micky2be sorry I haven't seen your message before ...

I opened : typescript: node_modules/@types/es6-promise/index.d.ts, line: 11
I have renamed : line11 : Promise in LOLPromise
and line 42 Promise in LOLPromise

but I'll just uninstall it for now apparently @schobbent has found the simplest solution.

**Comment by micky2be** [comment]
Alright, I removed es6-promise.
Will be part of the 0.4.3 release.
Seems to work on my side.
