### ISSUE TITLE
Sometimes getting Unauthorized on login

### ISSUE THREAD

**Issue by peteruithoven** [micky2be/superlogin-client#36]
Sometimes when I attempt a login it first does a refresh, which results in a Unauthorized, which then rejects my login attempt. 

It seems to depend on the contents of the superlogin session stored in localStorage. When the session is too old a refresh is triggered first, where login tokens are checked on the server. When these are invalid the Unauthorized error response is given. In these cases there won't be a login request triggered. 

The fact that this only happens when the session is too old made it hard to reproduce for me. 

I'm assuming the logins tokens become invalid after the [sessionLife setting](https://github.com/colinskow/superlogin/blob/master/config.example.js#L24-L25) is exceeded. 

Should there even be a refresh triggered when doing a login?

**Comment by micky2be** [comment]
I see, this is probably happening because you don't call refresh on application load.
Or do not use the checkExpired option.
If you do, that's probably because we forget to delete the session.

In any cases, it feels overkill to do a refresh on login anyways.

**Comment by peteruithoven** [comment]
I do call refresh on application load, but that doesn't seem to help. 
It looks like only the login function deletes the session when it fails, no other methods delete the session. 
I'm having a hard time assessing the ramifications, but maybe we should delete the session when refresh fails? Or maybe specifically when the response is `Unauthorized`? 

I'm also thinking there are more calls where refreshing the session doesn't make sense, like register. I just noticed I have the same unauthorized problem with registering for example. 
What about skipping refreshing the session for: 
- register
- forgotPassword
- resetPassword

(Looks like social auth doesn't have this problem.)

**Comment by peteruithoven** [comment]
I now see the session is also deleted in [_onLogout](https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L530-L534), which should be called in the injected error response handler: 
https://github.com/micky2be/superlogin-client/blob/master/src/index.js#L112-L117
But it looks like, for me, `response.status` is undefined for some reason. 

(I'm not using basic auth anymore)

**Comment by peteruithoven** [comment]
This library could really use some unit tests. It looks like this is also a subtle result of changes in Axios, like: https://github.com/micky2be/superlogin-client/issues/25. The `status` was moved, into a `response` object.

**Comment by micky2be** [comment]
For the unit test I agree. Just didn't have time to focus on it.

**Comment by micky2be** [comment]
Released in 0.4.3
