### ISSUE TITLE
addUserDB - Is it possible to achieve this from the client?

### ISSUE THREAD

**Issue by webnoob** [micky2be/superlogin-client#42]
Hi,

My application will allow an administrator to create users and allow access to the same database. With this in mind, I need the functionality of addUserDB so the new user can be associated with the current database. 

Is it possible to achieve this from the client?

**Comment by micky2be** [comment]
I'm afraid not. This is controlled on the backend side only.
You'll have to create an API yourself to do that

**Comment by webnoob** [comment]
No problem, as I learned more about this API I came to that conclusion as well. Thanks.
