### ISSUE TITLE
SuperLoginClient.refresh() and .logout()

### ISSUE THREAD

**Issue by webnoob** [micky2be/superlogin-client#43]
I want to call refresh at certain points in my app so that the token is refreshed and they have in turn done the required log in for the day (just in case the app goes offline).

The problem I have is I call `SuperLoginClient.login` and get my session back without issue but whenever I call `SuperLoginClient.refresh()` I get a `401 unauthorized`. This happens even if I call refresh immediately after logging in.

Edit: The same is also happening with `logout()` indicating it's anything that requires an authorised request.

**Comment by webnoob** [comment]
I've hooked up the `logout` event and it's being triggered and in turn shows the message `Logged out`. It appears to be the promise that's not resolving and just throwing a reject for some reason.

**Comment by micky2be** [comment]
Are you sure you are login then?
Do you have basic auth on your server?

**Comment by webnoob** [comment]
Well, I get my response back with my auth information so assume I'm logged in OK. Also, I'm able to query the database etc so the only things that seem to be wrong are the API calls that require authentication.

```
{
   "issued":1484562764380,
   "expires":1484649164380,
   "provider":"local",
   "ip":"::1",
   "token":"ndlediamadneremounteeter",
   "password":"42616eaeab2285f30ed9021a9dd414ba7da16f67",
   "user_id":"test13@test.com",
   "roles":[
      "user"
   ],
   "userDBs":{
      "msp":"https://ndlediamadneremounteeter:42616eaeab2285f30ed9021a9dd414ba7da16f67@webnoob.cloudant.com/"
   },
   "profile":{
      "companyName":"Test 13",
      "firstName":"test",
      "lastName":"13"
   },
   "serverTimeDiff":-414
}


```

**Comment by micky2be** [comment]
Would it be possible you setup your session length very short on your backend side?

**Comment by webnoob** [comment]
Sorry, didn't see this response. I'll take a look when I get back home.

**Comment by webnoob** [comment]
Ok, this is my security part of the config, it doesn't look too short:

```
  security: {
    maxFailedLogins: 3,
    lockoutTime: 600,
    tokenLife: 86400,
    loginOnRegistration: true
  }
```

**Comment by micky2be** [comment]
I'm very perplex about your issue.
You sure you are not doing something custom on your side.

**Comment by webnoob** [comment]
All I'm doing is calling:

```
SuperLoginClient.login({
  username: user,
  password: pass
})
```

To log the user in. Then, when the connection is online, I'll call:

```
SuperLoginClient.refresh().then(response => {
  console.log('REFRESHED user token')
  console.log(response)
  Store.dispatch('setUser', response)
})
```

Which results in the error. The Superlogin server is straight forward, it's pretty much the same as the one they suggest using:

```
var express = require('express');
var http = require('http');
var bodyParser = require('body-parser');
var logger = require('morgan');
var cors = require('cors');
var SuperLogin = require('superlogin');
var path = require('path');

var app = express();
app.set('port', process.env.PORT || 3000);
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cors());

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header('Access-Control-Allow-Methods', 'DELETE, PUT');
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});

var config = {
  local: {
    emailUsername: true,
    sendConfirmEmail: true,
    confirmEmailRedirectURL: 'http://localhost:8080/'
  },
  dbServer: {
    protocol: 'https://',
    host: 'myhost',
    user: 'myuser',
    password: 'mypass!',
    cloudant: true,
    userDB: 'sl-users'
  },
  mailer: {
    fromEmail: 'from@from',
    options: {
      host: 'mailhost',
      port: '25',
      auth: {
        user: 'asd',
        pass: 'asd'
      }
    }
  },
  security: {
    maxFailedLogins: 3,
    lockoutTime: 600,
    tokenLife: 86400,
    loginOnRegistration: true
  },
  userDBs: {
    defaultDBs: {
      private: ['DB']
    },
    model: {
      _default: {
        permissions: ['_reader', '_replicator', '_writer']
      }
    }
  },
  providers: {
    local: true
  },
  userModel: {
    whitelist: ['profile.companyName', 'profile.firstName', 'profile.lastName', 'profile.preferences']
  }
}

// Initialize SuperLogin
var superlogin = new SuperLogin(config);

// Mount SuperLogin's routes to our app
app.use('/auth', superlogin.router);

app.listen(app.get('port'));
console.log("App listening on " + app.get('port'));
```

**Comment by micky2be** [comment]
I think you should avoid calling refresh.
If you add the option `checkExpired` to true, it will check if there is an active session.
And then you should probably setup your store by listening to the 'login' event.

Hope it will fix your problem.

**Comment by webnoob** [comment]
I've got back to the point where I can test this freely now.
I've tried not calling refresh and setting `checkExpired = true` but now my session is constantly being logged out. The logout event is being called with the message `Session Expired`.

To test, I'm using a session time of 60 seconds and a `refreshThreshold` of `0.5`. I assume that won't cause any problems?

**Comment by clariontools** [comment]
@webnoob 

> To test, I'm using a session time of 60 seconds and a  refreshThreshold  of  0.5 . I assume that won't cause any problems?

A short session time should not be a problem for testing, only makes it easier to track down bugs :smile: .  Based on my testing the problem is `checkExpired = true `as it is documented to 

> SuperLogin will automatically refresh the token. ... When authenticated, the token expiration is automatically checked on every request.

The key here is **_every request_**, so that is whenever you hit the api.  What is happening (_I surmise_) is the token already expired, but the `checkExpired = true` forces a call to /auth/refresh, but with an expired token a call to checkExpired() checks if the session has expired and logs out if the access token is no longer valid.  Of course if your session has not expired that is great and as long as you keep hitting the api and regular intervals, your session expiration will be extended.

Based on my testing you should keep in mind that once the session is expired, all bets are off, calling the api with an expired session will deauthorized.  Seems like another issue is that once a session is expired it becomes deauthorized and cannot be properly logged out to remove the session from the server store and CouchDB (not sure how Cloudant works).

**Comment by clariontools** [comment]
@webnoob - Another issue that would exacerbate your problem is described here by @peteruithoven in issue #59 with a fix on #60 that would also require you to use @peteruithoven [Doodle3D](https://github.com/Doodle3D/superlogin/network) fork that includes the unmerged [superlogin PR163](https://github.com/colinskow/superlogin/pull/163).  I suppose @webnoob you have moved on to bigger and better things, but anyone that stumbles on this same issue may benefit. :beer:

**Comment by webnoob** [comment]
Thanks for your response @clariontools. I've not moved on, was just on different areas of my app and needed to focus.

I see issue 59 and 60 could cause problems but not in this case at least. 

Putting `.refresh()` aside for now, why can't I simply call `superLoginClient.logout()`? CheckedExpired is now false but I still get an error saying `401 Unauthorized`. This is happening on a session that I have only just logged in with (and with a normal session time, not a small test value).

**Comment by webnoob** [comment]
Ok, I've come back to this now. I've managed to get a working refresh but not via superlogin-client so I'm happy superlogin is working but there is something awry with the superlogin-client.

This is my working code (where $http is Axios):

```
var bearer = `Bearer ${this.getUserSession().token}:${this.getUserSession().password}`
      var config = {
        headers: {'Authorization': bearer}
      }
      console.log(config)
      return this.$http.post('http://localhost:4000/auth/refresh', {}, config).then(r => {
        console.log(r)
      })
```

This however returns unauthorized:

```
this.superLoginClient.refresh().then(response => {
  console.log('REFRESHED user token')
  console.log(response)
})
```

**Comment by webnoob** [comment]
Ok, fixed it. Looked at the super login client source code and noticed the endpoint check.

Basically, in my config, I hadn't added my endpoints properly - I put this down as my cloudant endpoint but it's my API endpoint it needed, like so:

```
endpoints: ['localhost:4000'],
```

This meant that it wasn't adding the authorization header.
