### ISSUE TITLE
Documentation bug: event callbacks should be without `event` argument

### ISSUE THREAD

**Issue by mnasyrov** [micky2be/superlogin-client#47]
[README](README.md) specifies that event callbacks receive `event` object as the first argument and the second one is data:
``` javascript
superlogin.on('login', function(event, session) { ... });
superlogin.on('logout', function(event, message) { ... });
superlogin.on('refresh', function(event, newSession) { ... });
superlogin.on('link', function(event, provider) { ... });
```

Actually, data is passed as the first argument and the second one is `undefined` always. 
It seems a copy from [ng-superlogin](https://github.com/colinskow/ng-superlogin).

**Comment by micky2be** [comment]
Yes, my bad.
Forgot to update the documentation accordingly.
