### ISSUE TITLE
Documentation for Angular2 wanted

### ISSUE THREAD

**Issue by jj-julia** [micky2be/superlogin-client#51]
It is unclear to me how I am meant to import the superlogin-client in an angular2 project. Some more documentation would be nice.

**Comment by micky2be** [comment]
This library is not meant to be for AngularJS but more for Vanilla.
If someone would be kind enough to write a documentation for AngularJS I have nothing against adding it though.

**Comment by webnoob** [comment]
There is another library designed to integrate angular with Superlogin:

https://github.com/colinskow/ng-superlogin

**Comment by simonmcl** [comment]
@webnoob that link is for the AngularJS client, Angular(Angular >= 2.x.x) is not the same as AngularJS(Angular <= 1.x.x), they are extremely different technologies now. That won't work without having to hack around with upgrade libraries and modules etc.

Normally you can take an NPM such as this and import it using something like

```Typescript
Import * as superlogin from 'superlogin-client'
```

But this is causing errors for me, saying `configure` is not a function of `.../superlogin-client/....`. Typically a Typescript "Typings" module is required in cases like this. This would expose all the classes and functions in a manner that the typescript transpiler can read and understand.

I'm relatively new to Angular 2 myself, so i'm not sure if there are other solutions or how easy it would be to create a Typings module

**Comment by micky2be** [comment]
The definition file is available in this repo (https://github.com/micky2be/superlogin-client/blob/master/superlogin-client.d.ts)
Feel free to use.

Then a simple `import superlogin from 'superlogin-client';`

I'm not sure what I could do more within this library for documentation.
For other details you can always check Angular or Typescript documentation.
