### ISSUE TITLE
404 (Not Found) error on logout

### ISSUE THREAD

**Issue by AmandavZ** [micky2be/superlogin-client#52]
First off, thank you for the superlogin-client plugin. And secondly, I want to apologize upfront if my question might have a very obviously answer but I am really desperate. I'm also not sure if this should rather go to the Superlogin repo or Stackoverflow...

My app and my superlogin api is hosted on Heroku (my app(angular 2) and superlogin app are separate apps) and the db is a cloudant db. I have set up the superlogin config to look like this: 

     `   var config = {
        baseUrl: '/auth/',
        endpoints: ['my-superlogin-api.herokuapp.com'],
        checkExpired: 'stateChange',
        refreshThreshold: 0.5,
    };

    superlogin.configure(config);`

When calling the superlogin.logout(message) function, the url posts to my app url and not to the superlogin endpoint. Is this the reason why I get a 404 not found?

**Comment by micky2be** [comment]
There is no silly question, only silly answers.

You need to add the `serverUrl` value which in your case will be `'my-superlogin-api.herokuapp.com'`
By default it goes to same url than your app.

The endpoints value is to let know superlogin where to add the auth data.

```
var config = {
    serverUrl: 'my-superlogin-api.herokuapp.com',
    baseUrl: '/auth/',
    endpoints: ['my-superlogin-api.herokuapp.com'],
    checkExpired: true,
    refreshThreshold: 0.5,
};
```

**Comment by AmandavZ** [comment]
Thank you very much for your reply.

I added the serverURL and it points to the right url but I get a 401 Unauthorized error. I did add "Authorization" to the Access-Control-Allow-Headers in the Superlogin api but it didn't make a difference.  Must I append the Authorization to the headers and token in the client app within the logout function?

Thanking you again for your assistance.

**Comment by micky2be** [comment]
You shouldn't need to add anything yourself on the client, superlogin does it for you.
Try to set `serverUrl` to `'http://my-superlogin-api.herokuapp.com'`, you night need to have full url in there.

By the way, I don't remember 100% but the logout method might trigger a 401 error.
Which will log you out on the client.

**Comment by AmandavZ** [comment]
Thank you for your reply. I did change the serverURL but it did not make a difference. There are two logout calls: a preflighted OPTIONS request which goes through fine (204 no content response) and then the POST request which is the 401 error thereafter. Could this be the reason why I'm getting the 401 error?

**Comment by AmandavZ** [comment]
I got it working!!!!!! Thank you very much for your help! I wasn't calling the superlogin client api for login, but a custom login function. So when I changed the login function to superlogin.login(credentials), the logout worked.

**Comment by micky2be** [comment]
Great
