### ISSUE TITLE
config baseurl not working

### ISSUE THREAD

**Issue by dhndeveloper** [micky2be/superlogin-client#6]
I'm running superlogin with node on localhost:3000. I'm using Ionic 2 which is on localhost:8100.

I have this as my setup (I wanted to use "import superlogin from 'superlogin-client' but I was getting at type error that it couldn't be found.)

`var superlogin = require('superlogin-client').default;
superlogin.configure(config);

var config = {
// The base URL for the SuperLogin routes with leading and trailing slashes (defaults to '/auth/')
baseUrl: 'http://localhost:3000/auth/',
// A list of API endpoints to automatically add the Authorization header to
// By default the host the browser is pointed to will be added automatically
endpoints: ["localhost:3000"],
// Set this to true if you do not want the URL bar host automatically added to the list
//noDefaultEndpoint: false,
// Where to save your session token: localStorage ('local') or sessionStorage ('session'), default: 'local'
storage: 'local',
// The authentication providers that are supported by your SuperLogin host
providers: ['facebook', 'twitter'],
// Sets when to check if the session is expired. 'stateChange', 'startup' or nothing.
// 'stateChange' checks every time $stateChangeStart or $routeChangeStart is fired
// 'startup' checks just on app startup. If this is blank it will never check.
checkExpired: 'stateChange',
// A float that determines the percentage of a session duration, after which SuperLogin will automatically refresh the
// token. For example if a token was issued at 1pm and expires at 2pm, and the threshold is 0.5, the token will
// automatically refresh after 1:30pm. When authenticated, the token expiration is automatically checked on every
// request. You can do this manually by calling superlogin.checkRefresh(). Default: 0.5
refreshThreshold: 0.5
};
`

The only way I got it work was on line 68 of the index.js file was to change: 

config.baseUrl = config.baseUrl || '/auth/';

to 

config.baseUrl = http://localhost:3100/auth/ || '/auth/';

Before I did that I was getting an error that it could not POST to http://localhost:8100/auth/login and thats obviously because superlogin is running on 3100. I thought thats why you set the baseurl in the config object. 

Any ideas? I thought may be it was the ".default" I have at the end of "var superlogin = require('superlogin-client').default;" but it won't work without the .default.

**Comment by micky2be** [comment]
I have a similar setup.
You probably need to set `noDefaultEndpoint` to `true`

**Comment by audan2009** [comment]
That did not  work

**Comment by dhndeveloper** [comment]
that worked! thanks!
