### ISSUE TITLE
Custom Username and Password Field doesn't work

### ISSUE THREAD

**Issue by ThonyFD** [micky2be/superlogin-client#64]
When change the parameters **local.usernameField** and **local.passwordField** in SuperLogin the super login client doesn't work.

I think that a easy way to resolve it, is to add **local.usernameField** and **local.passwordField** to the config object of superlogin-client

**Comment by micky2be** [comment]
Should be an easy fix indeed.
Mind sending a PR since you already have a use case?

**Comment by ThonyFD** [comment]
No problem, I going to work on it
