### ISSUE TITLE
confirmEmail is mistaken with verifyEmail in your code.

### ISSUE THREAD

**Issue by numerized** [micky2be/superlogin-client#65]
Hi, 

The route in superlogin to confirm an email is : 
```http://XX.XX.XXX.XXX:3002/auth/confirm-email/[TOKEN]```

and in your code you try to confirm email with: 
```return this._http.get(`${this._config.baseUrl}/verify-email/${token}`)```

Which is not good, verify-email is used to check if an email is still available or taken, here is a copy paste from the superlogin docs.

```
GET /confirm-email/{token}

This link is included in the confirmation email, and will mark the user as confirmed. If local.confirmEmailRedirectURL is specified in your config, it will redirect to that location with ?success=true if successful or error={error}&message={msg} if it failed. Otherwise it will generate a standard JSON response.
```

**Comment by micky2be** [comment]
I don't think there is any mistake here.
The API `verifyEmail` use the `verify-email` endpoint.

There is no `confirmEmail` API because the endpoint is used with a link you receive by email. Hence the name.

I can add the method if you really want but that sounds weird to me.
