### ISSUE TITLE
config.checkExpired?

### ISSUE THREAD

**Issue by peteruithoven** [micky2be/superlogin-client#7]
The readme mentions:

```
// Sets when to check if the session is expired. 'stateChange', 'startup' or nothing.
// 'stateChange' checks every time $stateChangeStart or $routeChangeStart is fired
// 'startup' checks just on app startup. If this is blank it will never check.
  checkExpired: 'stateChange',
```

But when I look through the code checkExpired is only checked as boolean, and only in the configure call?

**Comment by micky2be** [comment]
Yes, my bad I forgot to update the Readme.
It's only made to check the session during the startup.

**Comment by peteruithoven** [comment]
Ah alright, thanks for the answer.
