### ISSUE TITLE
Why does npm superlogin-client/lib/index.js compile to es2015 module github src/index.js?

### ISSUE THREAD

**Issue by clariontools** [micky2be/superlogin-client#70]
@micky2be - Based on the package.json, the npm package is configured to compile to an es2015 esModule lib, so the code is quite different from the base in this repo src/index.js.

I am not sure, but this made it more difficult for me to use with Ionic 3 and I had to stub out all the methods in a separate provider so I could more easily make the calls.  Would it be easier to use the github index.js as is in general or specifically with Ionic 3 (angular 4)?  I do recall that I could not use a named export in Ionic 3 `import { superlogin } from 'superlogin-client';`, I had to use the default export syntax `import superlogin from 'superlogin-client';`.  Apparently, this is because there is something non-standard about the superlogin-client npm lib, at least according to Ionic.  This is from the Ionic docs:

> Using the named export pattern is preferred and considered best practice because it only imports/includes the portion of the library that is needed. This results in smaller, faster apps.

In some cases, importing a specific portion of a library isn’t possible. Typically, this is the case with older libraries written for the Node Environments that don’t follow the ES2015 Module standard.

Also this makes it really difficult to contribute and test if the git repo contains one version of the index.js and the npm lib is structured quite differently.  I would like to contribute some changes, but need some clarification :smile: .  If this is how it has to be, please provide some background on why, and some advice on the best way to configure development.  Thank you!

**Comment by micky2be** [comment]
Even if the code is different the functionality are exactly the same.

I'm not sure to understand what can be the difficulty with Ionic, If you install superlogin-client from npm.
The module is written with a default export, therefore you would have to use `import superlogin from 'superlogin-client';`, there is nothing special about it, it's pretty standard.
Is it a typescript issue of some sort?

As for development I would write some documentation on how to proceed but that is pretty simple.
In superlogin-client, do your bug fix / feature change and run `npm run compile`.
Then in your app run `npm install <superlogin-client folder>` to update the source or us a symlink if you prefer.

**Comment by clariontools** [comment]
@micky2be - I understand the functionality is the same, just caught me off guard when I saw it wasn't exactly the same, but figured out it was compiled after looking at the package.json.

> I'm not sure to understand what can be the difficulty with Ionic

I have it sorted out with a workaround that is working fine for now.  Mainly I was having trouble referencing the superlogin-client class when using dependency injection.  No problem to reference superlogin in my provider using `import superlogin from 'superlogin-client';`, but when I import my provider and use in other pages etc, through dependency injection, it does not see the superlogin class.  Could be a typescript thing, but I tried quite a few things before giving up and just stubbing out all the superlogin methods in my provider.

> As for development I would write some documentation on how to proceed but that is pretty simple.

That sounds easy enough.  I do have an issue that I would like to do a PR on, would you rather discuss it first before I attempt the PR?  I can create an issue first so I don't waste time if it is something that doesn't fit or would otherwise affect existing installations negatively.  :sushi:

**Comment by micky2be** [comment]
Sure, just open an issue first. It will help me for tracking too.

**Comment by clariontools** [comment]
@micky2be - Will open an issue for the enhancement/bug fix that I have worked on.  In the meantime, consider this closed, if I do come back and figure out a possibly better way to integrate with Ionic 3 or someone else has a good example that doesn't involve what I did to stub out the superlogin-client methods they could post it here.  Thanks!
