### ISSUE TITLE
logout with expired session leaves expired sessions in data store

### ISSUE THREAD

**Issue by clariontools** [micky2be/superlogin-client#71]
Calling logout (or any of the flavors) with an expired session first calls auth/refesh, which returns a 401 and deauthorizes the expired session.  The logout on the server side is never completed and the session store on the server and the session key in CouchDB _users remains along with the user db Members -> user reference in the _security doc.  This can be cleaned up if you call removeExpiredKeys() on the server, but while it is active, the _users session token becomes a security risk and it can cause significant clutter if you fail to implement removeExpiredKeys() on the server.

I have implemented and tested a fix that will do a normal logout (or any of the flavors) and remove all the session store from the relevant dbs.  I have only tested this on CouchDB, so I do not how it plays with Cloudant?  I could not see any downsides since the session is expired anyway, even if it is a hijacked session a call to logout would only mean that they could no longer use that session to access the CouchDB datastores.

Before a do a PR I could use some feedback on this, but again I do not see any downside of doing a proper logout.

**Comment by micky2be** [comment]
It sounds more like a backend problem to me.
Have you discussed about this on superlogin?

**Comment by clariontools** [comment]
I already have a fix with a few lines of code on superlogin-client, spent many hours tracking this down, so I know where the problem is.  Wanted to discuss it further based on my comments above to make sure it is something that you would be interested in, but it seems that it is not a common problem, so will just wait and see if others report it.  Thanks.
