### ISSUE TITLE
Modify logout to use optional ip filtering

### ISSUE THREAD

**Issue by clariontools** [micky2be/superlogin-client#72]
I am considering adding ip filtering to the logout calls, but this would first require modification of superlogin to work.  The idea is that since superlogin already stores the original ip address that started a session, you could use the ip to filter out calls to logoutAll or logoutOthers in the case where a user maybe logged in on separate devices.  Just thinking at this point and the ip could be used to do addition authentication as well to enhance security.  The ip is already stored by superlogin on the user sessions and even though I do not see it being leveraged, I think it was added for some future possible uses.  There is more related discussion I have added over at the[ superlogin repo issue 179](https://github.com/colinskow/superlogin/issues/179), that gives more background on how this came about.

This may not be a good idea because I suppose the ip could change from the time of login to eventual logout, so it may not be worth the effort.  In that case, using logoutAll and logoutOthers as they stand now assume that there is only ever one session active at any given time for one user, *but* the api _*does not*_ have an option to prevent more than one user from logging in with the same user pass.

The biggest downside of adding the ip filtering option on logoutAll and logoutOthers is that you may end up with orphaned sessions, but the bonus would be to allow a user to login on multiple devices and still be able to have a better chance of cleaning up any orphaned sessions by using logoutAll and logoutOthers.  I described some scenarios in the [superlogin 179 issue](https://github.com/colinskow/superlogin/issues/179), but would be interested in hearing any other take on the value of using the ip for this or any other purpose?

**Comment by micky2be** [comment]
This seems to be 100% backend related. Not sure what we can add here

**Comment by clariontools** [comment]
Only wanted to discuss it here because it would also require a change to superlogin-client, just changing the server would not be enough.
