### ISSUE TITLE
How to keep checking (and refreshing) session?

### ISSUE THREAD

**Issue by peteruithoven** [micky2be/superlogin-client#8]
Is there a recommend way to keep checking (and refreshing) the session?

There is an checkExpired config option, which when enabled will validate the session after configure, but this is only once, and I'm not sure if it refreshes the session when necessary.

**Comment by micky2be** [comment]
`refresh` will be triggered automatically on any call based on the `refreshThreshold` value (at 50% of the ttl by default).
You could set it to 0 (on every call) if you desire but I wouldn't recommend it (too heavy on the database)

**Comment by peteruithoven** [comment]
Ah alright, I sort of got that from the source code later on. I was confused, the original text made me search for a timing based system (setTimeout, setInterval), but when I didn't find this I assumed I had to do it manually. I'll try to do a suggestion for the readme. 
Very nice that this is handled automatically.
